name: Docker Build

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number for the release'
        required: true
        default: '1.0.0'

env:
  IMAGE_NAME: readme-generator-for-helm

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set VERSION environment variable
        run: echo "VERSION=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:latest --tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag ${{ env.IMAGE_NAME }}:latest $IMAGE_ID:latest
          docker tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }} $IMAGE_ID:${{ env.VERSION }}
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:${{ env.VERSION }}
